version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rails_sample
    ports:
      - "3000:3000"
    depends_on:
      - db